### ISSUE TITLE
Create Java WS to use OrderRepo 

### ISSUE THREAD

**Issue by mrrk181** [mrrk181/JaxWs#1]
Implement following methods in the webservice:- ((these have been implemented in the OrderRepo)
o Retrieve order by id
o Retrieve all products
o Retrieve all customers
o Add a new customer 
o Add a new product
o Add a new order

**Comment by hamxabaig** [comment]
@mrrk181 what is JAVA WS?

**Comment by hamxabaig** [comment]
@mrrk181 😂
